export const contentMenu = [
  // components
  { category: "components", title: "accordion", description: "description accordion", href: "/accordion" },
  { category: "components", title: "carousel", description: "description carousel", href: "/carousel" },
  { category: "components", title: "navbar", description: "description navbar", href: "/navbar" },
  { category: "components", title: "navbar2", description: "description navbar2", href: "/navbar-2" },
  { category: "components", title: "pagination", description: "description pagination", href: "/pagination" },
  // tips
  { category: "tips", title: "sticky", description: "Description sticky", href: "/sticky" },
  { category: "tips", title: "copy alert", description: "Description copy alert", href: "/copy-alert" },
  { category: "tips", title: "use in view", description: "Description use in view", href: "/use-in-view" },
  { category: "tips", title: "object tips", description: "Description object tips", href: "/object-tips" },
  // apps
  { category: "apps", title: "clock", description: "Description color", href: "/clock" },
  { category: "apps", title: "stopwatch", description: "Description stopwatch", href: "/stopwatch" },
  { category: "apps", title: "symbol color", description: "Description symbol color", href: "/symbol-color" },
  // framer
  { category: "framer", title: "bulb 1", description: "Description bulb 1", href: "/bulb-1" },
  { category: "framer", title: "bulb 2", description: "Description bulb 2", href: "/bulb-2" },
  { category: "framer", title: "element scroll", description: "Description element scroll", href: "/element-scroll" },
  { category: "framer", title: "float nav 1", description: "Description float nav 1", href: "/float-nav-1" },
  { category: "framer", title: "float nav 2", description: "Description float nav 2", href: "/float-nav-2" },
  { category: "framer", title: "float nav 3", description: "Description float nav 3", href: "/float-nav-3" },
  { category: "framer", title: "parallax", description: "Description parallax", href: "/parallax" },
  { category: "framer", title: "progress bar 1", description: "Description progress bar 1", href: "/progress-bar-1" },
  // react
  { category: "react", title: "memo", description: "Description memo", href: "/memo" },
  { category: "react", title: "use callback", description: "Description use callback", href: "/use-callback" },
  { category: "react", title: "use context", description: "Description use context", href: "/use-context" },
  { category: "react", title: "use memo", description: "Description use memo", href: "/use-memo" },
  { category: "react", title: "use reducer", description: "Description use reducer", href: "/use-reducer" },
  { category: "react", title: "use ref", description: "Description use ref", href: "/use-ref" },
  // others
  { category: "others", title: "callendar", description: "Description callendar", href: "/callendar" },
  { category: "others", title: "flip text", description: "Description flip text", href: "/flip-text" },
  { category: "others", title: "svg", description: "Description svg", href: "/svg" },
  { category: "others", title: "canvas", description: "Description canvas", href: "/canvas" },
  { category: "others", title: "css background", description: "Description css background", href: "/css-background" },
  { category: "others", title: "landing1", description: "Description landing 1", href: "/landing-1" },
  { category: "others", title: "landing2", description: "Description landing 2", href: "/landing-2" },
  { category: "others", title: "typescript", description: "Description typescript", href: "/typescript" },
  // static web
  {
    category: "static web",
    title: "accordion static",
    description: "Description accordion static",
    href: "/static-web/accordion.html",
  },
  {
    category: "static web",
    title: "carousel static",
    description: "Description carousel static",
    href: "/static-web/carousel.html",
  },
  {
    category: "static web",
    title: "carousel2 static",
    description: "Description carousel2 static",
    href: "/static-web/carousel2.html",
  },
  {
    category: "static web",
    title: "Mr Web Designer 2",
    description: "Description Mr Web Designer 2",
    href: "/static-web/mrwd2/index.html",
  },
  {
    category: "static web",
    title: "Nurul Iman",
    description: "Description Nurul Iman",
    href: "/static-web/nuruliman/index.html",
  },
  {
    category: "static web",
    title: "Wpu Bootstrap 1",
    description: "Description Wpu Bootstrap 1",
    href: "/static-web/wpu-bs1/index.html",
  },
  {
    category: "static web",
    title: "Wpu Bootstrap 2",
    description: "Description Wpu Bootstrap 2",
    href: "/static-web/wpu-bs2/index.html",
  },
  {
    category: "static web",
    title: "Wpu Materialize 1",
    description: "Description Wpu Materialize 1",
    href: "/static-web/wpu-mtrz1/index.html",
  },
  {
    category: "static web",
    title: "Omdbapi",
    description: "Description Omdbapi",
    href: "/static-web/omdbapi/index.html",
  },
  {
    category: "static web",
    title: "Tugas 1 HTML",
    description: "Description Tugas 1 HTML",
    href: "/static-web/tugas1-html/index.html",
  },
  {
    category: "static web",
    title: "Tugas 2 Bootstrap",
    description: "Description Tugas 2 Bootstrap",
    href: "/static-web/tugas2-bootstrap/index.html",
  },
  {
    category: "static web",
    title: "Tugas 3 JS Basic",
    description: "Description Tugas 3 JS Basic",
    href: "/static-web/tugas3-jsbasic/index.html",
  },
  {
    category: "static web",
    title: "Tugas 4 Table",
    description: "Description Tugas 4 Table",
    href: "/static-web/tugas4-miniLibrary/index.html",
  },
  {
    category: "static web",
    title: "Tugas 5 Jsonplaceholder",
    description: "Description Tugas 5 Jsonplaceholder",
    href: "/static-web/tugas6-jsonplaceholder/index.html",
  },
  {
    category: "static web",
    title: "Tugas 6 Portal",
    description: "Description Tugas 6 Portal",
    href: "/static-web/tugas7-portalBeritaPromise/index.html",
  },
];
